version: '3'

services:
  postgres_db:
    container_name: competition-db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./migrate/1_init_db.sql:/docker-entrypoint-initdb.d/structer.sql

#  service:
#    container_name: service-competition
#    build: .
#    env_file:
#      - .env
#    ports:
#      - "${HTTP_PORT}:${HTTP_PORT}"
#    depends_on:
#      - postgres_db
#    restart: unless-stopped
